Repository ajktown/ConsistencyGPT, pull requests merged in 2024-02, with the labels that each got.

#5 Push image commands and k8s file
  .vscode/settings.json
  Dockerfile
  README.md
  k8s/deployment.yaml
  k8s/service.yaml
Labels: documentation, enhancement

#4 Shows 2024 post word consistency of wordnote gpt
  .vscode/settings.json
  src/api/action-groups/get-action-groups.api.ts
  src/components/atom_ask_to_add_word_button/index.tsx
  src/components/atom_refresh_button/index.tsx
  src/components/molecule_activity_calendar/index.tsx
  src/components/molecule_activity_calendar/index.unknown.tsx
  src/components/organism_activity_calendar_frame/index.style.ts
  src/components/organism_activity_calendar_frame/index.tsx
  src/hooks/action-group/use-action-groups.hook.ts
  src/lambdas/axios-request-success.lambda.ts
  src/lambdas/get-env.lambda.ts
  src/recoil/action-groups/action-groups.state.ts
  src/recoil/index.keys.ts
Labels: enhancement

#9 Handle API Change "Standardize Action Group and Action"
  src/api/action-groups/get-action-group-daily-post-word-challenge.api.ts
  src/api/action-groups/get-action-groups.api.ts
  src/api/action-groups/index.interface.ts
  src/components/atom_ask_to_add_word_button/index.tsx
  src/components/atom_refresh_button/index.tsx
  src/components/molecule_activity_calendar/index.tsx
  src/constants/action-group.constant.ts
  src/hooks/action-group/use-action-groups.hook.ts
  src/hooks/action-group/use-daily-post-word-challenge.hook.ts
  src/recoil/action-groups/action-groups.state.ts
Labels: enhancement

#10 List of Action Groups You Own
  src/api/action-groups/get-action-group-by-id.api.ts
  src/api/action-groups/get-action-group-ids.api.ts
  src/components/molecule_activity_calendar/index.by-id.tsx
  src/components/organism_activity_calendar_frame/index.daily-post-word-challenge.tsx
  src/components/organism_activity_calendar_frame/index.tsx
  src/hooks/action-group/use-action-group-by-id.hook.ts
  src/hooks/action-group/use-action-group-ids.hook.ts
  src/layouts/index.tsx
  src/recoil/action-groups/action-groups.state.ts
  src/recoil/index.keys.ts
Labels: enhancement

#13 Kubernetes like issue for this repository
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/dependency.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/infrastructure.yaml
  .github/ISSUE_TEMPLATE/performance.yaml
  .github/ISSUE_TEMPLATE/refactor.yaml
Labels: documentation

#14 New CGT Icon Color
  public/favicon.ico
  public/favicon_archived/android-chrome-192x192.png
  public/favicon_archived/android-chrome-512x512.png
  public/favicon_archived/apple-touch-icon.png
  public/favicon_archived/favicon-16x16.png
  public/favicon_archived/favicon-32x32.png
  public/favicon_archived/favicon.ico
Labels: enhancement

#15 Bigbang change: Create/Get Action Groups
  .vscode/settings.json
  src/api/action-groups/get-action-group-ids.api.ts
  src/api/action-groups/index.interface.ts
  src/api/action-groups/post-action-by-action-group-id.api.ts
  src/api/action-groups/post-action-group.api.ts
  src/api/rituals/get-rituals.api.ts
  src/atoms/StyledCircularButton.tsx
  src/atoms/StyledTextWithPrefixButton.tsx
  src/components/atom_ask_to_add_word_button/index.tsx
  src/components/dialog_post_action_group/index.tsx
  src/components/molecule_action_group_card/index.buttons.tsx
  src/components/molecule_action_group_card/index.special-message.tsx
  src/components/molecule_action_group_card/index.title.tsx
  src/components/molecule_action_group_card/index.tsx
  src/components/molecule_activity_calendar/index.by-id.tsx
  src/components/molecule_activity_calendar/index.tsx
  src/components/organism_activity_calendar_frame/index.daily-post-word-challenge.tsx
  src/components/organism_activity_calendar_frame/index.tsx
  src/components/organism_appbar/index.tsx
  src/components/organism_rituals_frame/index.refresh-button.tsx
  src/components/organism_rituals_frame/index.tsx
  src/handlers/time.handler.ts
  src/hooks/action-group/use-action-group-by-id.hook.ts
  src/hooks/action-group/use-action-group-ids.hook.ts
  src/hooks/action-group/use-daily-post-word-challenge.hook.ts
  src/hooks/action-group/use-post-action-group.hook.ts
  src/hooks/ritual/use-rituals.hook.ts
  src/layouts/index.tsx
  src/molecules/StyledAppbar.tsx
  src/recoil/action-groups/action-groups.state.ts
Labels: enhancement

#18 GitHub Icon
  src/components/atom_appbar_parts/index.github_icon.tsx
  src/components/organism_appbar/index.tsx
Labels: enhancement

#19 Time picker UI should be implemented for the time UI
  package.json
  src/atoms/StyledTimePicker.tsx
  src/components/dialog_post_action_group/index.tsx
  yarn.lock
Labels: enhancement

#20 Yarn Latest Feb 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency
